---
- hosts: all
  gather_facts: true
  connection: oc

  tasks:
    - name: Ensure the myapp Namespace exists.
      redhat.openshift.k8s:
        api_version: v1
        kind: Namespace
        name: test123
        state: present
